addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.4")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "1.1")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC4")
addSbtPlugin("com.lucidchart" % "sbt-scalafmt-coursier" % "1.6-mp")
